// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haffkdehfhphiysljdbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZmZrZGVoZmhwaGl5c2xqZGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODM5NzMsImV4cCI6MjA2MDA1OTk3M30.yVTndl78RQwIdpIfJVllPKix63_1FHHUrdRqYOo-7O4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);